import React from 'react';
import type { Message, User } from '../types';
import { Role } from '../types';
import { BotIcon, GridIcon } from './icons';
import UserAvatar from './UserAvatar';

interface MessageBubbleProps {
  message: Message;
  user: User | null;
}

const MessageBubble: React.FC<MessageBubbleProps> = ({ message, user }) => {
  const isUser = message.role === Role.USER;

  const renderContent = () => {
    switch (message.type) {
      case 'image':
        return (
          <img 
            src={message.imageUrl} 
            alt="Generated by AI" 
            className="rounded-lg max-w-sm w-full h-auto"
          />
        );
      case 'tool-call':
        return (
            <div className="flex items-center gap-2 text-secondary italic">
                <GridIcon className="w-4 h-4 animate-spin" />
                <span>{message.content}</span>
            </div>
        )
      case 'text':
      default:
        return <p className="whitespace-pre-wrap leading-relaxed">{message.content}</p>;
    }
  };
  
  const bubbleClasses = isUser
    ? 'bg-user-bubble text-background font-medium'
    : 'bg-model-bubble text-primary';
  
  const containerClasses = isUser 
    ? 'justify-end' 
    : 'justify-start';

  return (
    <div className={`flex items-start gap-4 animate-fade-in ${containerClasses}`}>
      {!isUser && (
        <div className="flex-shrink-0 w-9 h-9 rounded-full bg-surface border border-white/10 flex items-center justify-center">
          <BotIcon className="w-5 h-5 text-accent" />
        </div>
      )}
      <div className={`max-w-md md:max-w-2xl px-5 py-3 rounded-2xl shadow-md ${bubbleClasses}`}>
        {renderContent()}
      </div>
      {isUser && <UserAvatar user={user} />}
    </div>
  );
};

export default MessageBubble;
